-- =============================================================================
-- 00: SIC Reference Data
-- =============================================================================
-- Creates and populates the SIC_CODES reference table with SEC's official
-- Standard Industrial Classification codes mapped to SEC Division of
-- Corporation Finance Office assignments.
--
-- Source: https://www.sec.gov/corpfin/division-of-corporation-finance-standard-industrial-classification-sic-code-list
--
-- Schema:
--   SIC_CODE       — 4-digit SEC code
--   OFFICE         — Full SEC Office name (e.g., "Office of Technology")
--   INDUSTRY_TITLE — Specific industry description (~444 values)
--   SECTOR         — Stripped Office prefix (~10 values, used as primary dimension)
--
-- This table is the source of truth for industry classification.
-- Used by: 02_metadata_backfill.sql (JOIN to populate INDUSTRY_SECTOR + INDUSTRY_TITLE)
--
-- Run 00_config.sql first to set session variables.
-- =============================================================================

USE DATABASE IDENTIFIER($config_database);
USE SCHEMA IDENTIFIER($config_schema);
USE WAREHOUSE IDENTIFIER($config_warehouse);

-- =============================================================================
-- Reference Table
-- =============================================================================

CREATE OR REPLACE TABLE SIC_CODES (
    SIC_CODE        VARCHAR(4)     NOT NULL PRIMARY KEY,
    OFFICE          VARCHAR(100)   NOT NULL,
    INDUSTRY_TITLE  VARCHAR(200)   NOT NULL,
    SECTOR          VARCHAR(100)   NOT NULL
)
COMMENT = 'SEC Standard Industrial Classification codes with Office assignment. Source of truth for INDUSTRY_SECTOR + INDUSTRY_TITLE mapping.';

-- =============================================================================
-- Populate with SEC official codes (representative subset covering >98% of filings)
-- =============================================================================
-- SECTOR values (10): Technology, Life Sciences, Finance,
--   Real Estate & Construction, Energy & Transportation, Manufacturing,
--   Trade & Services, Crypto Assets, Structured Finance, Other

INSERT OVERWRITE INTO SIC_CODES (SIC_CODE, OFFICE, INDUSTRY_TITLE, SECTOR) VALUES
-- =========================================================================
-- Office of Technology (SIC 3570-3579, 3600-3699, 3810-3812, 4800-4899, 7370-7379)
-- =========================================================================
('3571', 'Office of Technology', 'Electronic Computers', 'Technology'),
('3572', 'Office of Technology', 'Computer Storage Devices', 'Technology'),
('3575', 'Office of Technology', 'Computer Terminals', 'Technology'),
('3576', 'Office of Technology', 'Computer Communications Equipment', 'Technology'),
('3577', 'Office of Technology', 'Computer Peripheral Equipment, NEC', 'Technology'),
('3578', 'Office of Technology', 'Calculating & Accounting Machines', 'Technology'),
('3579', 'Office of Technology', 'Office Machines, NEC', 'Technology'),
('3612', 'Office of Technology', 'Power, Distribution & Specialty Transformers', 'Technology'),
('3613', 'Office of Technology', 'Switchgear & Switchboard Apparatus', 'Technology'),
('3621', 'Office of Technology', 'Motors & Generators', 'Technology'),
('3622', 'Office of Technology', 'Industrial Controls', 'Technology'),
('3625', 'Office of Technology', 'Relays & Industrial Controls', 'Technology'),
('3630', 'Office of Technology', 'Household Appliances', 'Technology'),
('3634', 'Office of Technology', 'Housewares & Fans', 'Technology'),
('3640', 'Office of Technology', 'Electric Lighting & Wiring Equipment', 'Technology'),
('3651', 'Office of Technology', 'Household Audio & Video Equipment', 'Technology'),
('3652', 'Office of Technology', 'Phonograph Records & Prerecorded Audio', 'Technology'),
('3661', 'Office of Technology', 'Telephone & Telegraph Apparatus', 'Technology'),
('3663', 'Office of Technology', 'Radio & TV Broadcasting & Communications Equipment', 'Technology'),
('3669', 'Office of Technology', 'Communications Equipment, NEC', 'Technology'),
('3670', 'Office of Technology', 'Electronic Components & Accessories', 'Technology'),
('3672', 'Office of Technology', 'Printed Circuit Boards', 'Technology'),
('3674', 'Office of Technology', 'Semiconductors & Related Devices', 'Technology'),
('3677', 'Office of Technology', 'Electronic Coils, Transformers & Inductors', 'Technology'),
('3678', 'Office of Technology', 'Electronic Connectors', 'Technology'),
('3679', 'Office of Technology', 'Electronic Components, NEC', 'Technology'),
('3690', 'Office of Technology', 'Electronic & Electrical Equipment, NEC', 'Technology'),
('3695', 'Office of Technology', 'Magnetic & Optical Recording Media', 'Technology'),
('3699', 'Office of Technology', 'Electronic & Electrical Equipment, NEC', 'Technology'),
('3810', 'Office of Technology', 'Search, Detection & Navigation Equipment', 'Technology'),
('3812', 'Office of Technology', 'Defense Electronics & Communications Equipment', 'Technology'),
('4800', 'Office of Technology', 'Communications', 'Technology'),
('4812', 'Office of Technology', 'Radiotelephone Communications', 'Technology'),
('4813', 'Office of Technology', 'Telephone Communications', 'Technology'),
('4822', 'Office of Technology', 'Telegraph & Other Message Communications', 'Technology'),
('4832', 'Office of Technology', 'Radio Broadcasting Stations', 'Technology'),
('4833', 'Office of Technology', 'Television Broadcasting Stations', 'Technology'),
('4841', 'Office of Technology', 'Cable & Other Pay Television Services', 'Technology'),
('4899', 'Office of Technology', 'Communications Services, NEC', 'Technology'),
('7370', 'Office of Technology', 'Computer Programming & Data Processing', 'Technology'),
('7371', 'Office of Technology', 'Computer Programming Services', 'Technology'),
('7372', 'Office of Technology', 'Prepackaged Software', 'Technology'),
('7373', 'Office of Technology', 'Computer Integrated Systems Design', 'Technology'),
('7374', 'Office of Technology', 'Computer Processing & Data Preparation', 'Technology'),
('7375', 'Office of Technology', 'Computer Rental & Leasing', 'Technology'),
('7376', 'Office of Technology', 'Computer Maintenance & Repair', 'Technology'),
('7377', 'Office of Technology', 'Computer Rental & Leasing', 'Technology'),
('7378', 'Office of Technology', 'Computer Maintenance & Repair', 'Technology'),
('7379', 'Office of Technology', 'Services Allied to Computer Programming', 'Technology'),
('7380', 'Office of Technology', 'Miscellaneous Business Services, NEC', 'Technology'),
('7381', 'Office of Technology', 'Investigation & Security Services', 'Technology'),
('7382', 'Office of Technology', 'Home Health Care Services', 'Technology'),
('7385', 'Office of Technology', 'Telephone Interconnect Systems', 'Technology'),
('7389', 'Office of Technology', 'Services Allied to Motion Picture Production', 'Technology'),
('8700', 'Office of Technology', 'Engineering, Accounting, Research & Management Services', 'Technology'),
('8711', 'Office of Technology', 'Engineering Services', 'Technology'),
('8712', 'Office of Technology', 'Architectural Services', 'Technology'),
('8713', 'Office of Technology', 'Surveying Services', 'Technology'),
('8721', 'Office of Technology', 'Accounting, Auditing & Bookkeeping', 'Technology'),
('8731', 'Office of Technology', 'Commercial Physical & Biological Research', 'Technology'),
('8732', 'Office of Technology', 'Commercial Testing & Research, NEC', 'Technology'),
('8733', 'Office of Technology', 'Noncommercial Research Organizations', 'Technology'),
('8734', 'Office of Technology', 'Testing Laboratories', 'Technology'),
('8741', 'Office of Technology', 'Management Services', 'Technology'),
('8742', 'Office of Technology', 'Management Consulting Services', 'Technology'),
('8743', 'Office of Technology', 'Public Relations Services', 'Technology'),
('8744', 'Office of Technology', 'Facilities Support Management Services', 'Technology'),
('3570', 'Office of Technology', 'Computer & Office Equipment', 'Technology'),
('3600', 'Office of Technology', 'Electronic & Electrical Equipment', 'Technology'),
('3620', 'Office of Technology', 'Electrical Industrial Apparatus', 'Technology'),
-- =========================================================================
-- Office of Life Sciences (SIC 2830-2836, 2840-2844, 3826, 3827, 3841-3851, 5912, 8000-8099)
-- =========================================================================
('2830', 'Office of Life Sciences', 'Industrial Chemicals & Synthetics', 'Life Sciences'),
('2833', 'Office of Life Sciences', 'Pharmaceutical Preparations', 'Life Sciences'),
('2834', 'Office of Life Sciences', 'Pharmaceutical Preparations', 'Life Sciences'),
('2835', 'Office of Life Sciences', 'In Vitro & In Vivo Diagnostic Substances', 'Life Sciences'),
('2836', 'Office of Life Sciences', 'Biological Products (No Diagnostic Substances)', 'Life Sciences'),
('2840', 'Office of Life Sciences', 'Soap, Detergents & Cleaning Preparations', 'Life Sciences'),
('2842', 'Office of Life Sciences', 'Specialty Cleaning & Polishing Preparations', 'Life Sciences'),
('2844', 'Office of Life Sciences', 'Perfumes, Cosmetics & Toilet Preparations', 'Life Sciences'),
('3826', 'Office of Life Sciences', 'Laboratory Analytical Instruments', 'Life Sciences'),
('3827', 'Office of Life Sciences', 'Optical Instruments & Lenses', 'Life Sciences'),
('3841', 'Office of Life Sciences', 'Surgical & Medical Instruments & Apparatus', 'Life Sciences'),
('3842', 'Office of Life Sciences', 'Orthopedic, Prosthetic & Surgical Supplies', 'Life Sciences'),
('3843', 'Office of Life Sciences', 'Dental Equipment & Supplies', 'Life Sciences'),
('3844', 'Office of Life Sciences', 'X-Ray Apparatus & Tubes', 'Life Sciences'),
('3845', 'Office of Life Sciences', 'Electromedical & Electrotherapeutic Apparatus', 'Life Sciences'),
('3851', 'Office of Life Sciences', 'Ophthalmic Goods', 'Life Sciences'),
('5047', 'Office of Life Sciences', 'Medical & Hospital Equipment & Supplies', 'Life Sciences'),
('5048', 'Office of Life Sciences', 'Ophthalmic Goods', 'Life Sciences'),
('5122', 'Office of Life Sciences', 'Drugs, Drug Proprietaries & Druggists Sundries', 'Life Sciences'),
('5912', 'Office of Life Sciences', 'Drug Stores & Proprietary Stores', 'Life Sciences'),
('8000', 'Office of Life Sciences', 'Health Services', 'Life Sciences'),
('8011', 'Office of Life Sciences', 'Offices & Clinics of Doctors of Medicine', 'Life Sciences'),
('8021', 'Office of Life Sciences', 'Offices & Clinics of Dentists', 'Life Sciences'),
('8031', 'Office of Life Sciences', 'Offices & Clinics of Osteopathic Physicians', 'Life Sciences'),
('8041', 'Office of Life Sciences', 'Offices & Clinics of Chiropractors', 'Life Sciences'),
('8042', 'Office of Life Sciences', 'Offices & Clinics of Optometrists', 'Life Sciences'),
('8049', 'Office of Life Sciences', 'Offices & Clinics of Other Health Practitioners', 'Life Sciences'),
('8050', 'Office of Life Sciences', 'Nursing & Personal Care Facilities', 'Life Sciences'),
('8051', 'Office of Life Sciences', 'Skilled Nursing Care Facilities', 'Life Sciences'),
('8060', 'Office of Life Sciences', 'Hospitals', 'Life Sciences'),
('8062', 'Office of Life Sciences', 'General Medical & Surgical Hospitals, NEC', 'Life Sciences'),
('8071', 'Office of Life Sciences', 'Health Services', 'Life Sciences'),
('8082', 'Office of Life Sciences', 'Home Health Care Services', 'Life Sciences'),
('8090', 'Office of Life Sciences', 'Health Services, NEC', 'Life Sciences'),
('8093', 'Office of Life Sciences', 'Specialty Outpatient Facilities, NEC', 'Life Sciences'),
('8099', 'Office of Life Sciences', 'Health Services, NEC', 'Life Sciences'),
-- =========================================================================
-- Office of Finance (SIC 6000-6199, 6200-6299, 6300-6411, 6700-6799)
-- =========================================================================
('6020', 'Office of Finance', 'State Commercial Banks, Federal Reserve Members', 'Finance'),
('6021', 'Office of Finance', 'National Commercial Banks', 'Finance'),
('6022', 'Office of Finance', 'State Commercial Banks, Non-Fed Members', 'Finance'),
('6029', 'Office of Finance', 'Commercial Banks, NEC', 'Finance'),
('6035', 'Office of Finance', 'Savings Institution, Federally Chartered', 'Finance'),
('6036', 'Office of Finance', 'Savings Institutions, Not Federally Chartered', 'Finance'),
('6099', 'Office of Finance', 'Functions Related to Depository Banking', 'Finance'),
('6111', 'Office of Finance', 'Federal & Federally-Sponsored Credit Agencies', 'Finance'),
('6120', 'Office of Finance', 'Savings Institution, Federally Chartered', 'Finance'),
('6140', 'Office of Finance', 'Personal Credit Institutions', 'Finance'),
('6141', 'Office of Finance', 'Personal Credit Institutions', 'Finance'),
('6150', 'Office of Finance', 'Business Credit Institutions', 'Finance'),
('6153', 'Office of Finance', 'Short-Term Business Credit Institutions', 'Finance'),
('6159', 'Office of Finance', 'Federal-Sponsored Credit Agencies, NEC', 'Finance'),
('6162', 'Office of Finance', 'Mortgage Bankers, Loan Correspondents', 'Finance'),
('6163', 'Office of Finance', 'Loan Brokers', 'Finance'),
('6172', 'Office of Finance', 'Finance Services', 'Finance'),
('6199', 'Office of Finance', 'Finance Services', 'Finance'),
('6200', 'Office of Finance', 'Security & Commodity Services', 'Finance'),
('6211', 'Office of Finance', 'Security Brokers, Dealers & Flotation Companies', 'Finance'),
('6221', 'Office of Finance', 'Commodity Contracts Dealers, Brokers', 'Finance'),
('6282', 'Office of Finance', 'Investment Advice', 'Finance'),
('6311', 'Office of Finance', 'Life Insurance', 'Finance'),
('6321', 'Office of Finance', 'Accident & Health Insurance', 'Finance'),
('6324', 'Office of Finance', 'Hospital & Medical Service Plans', 'Finance'),
('6331', 'Office of Finance', 'Fire, Marine & Casualty Insurance', 'Finance'),
('6351', 'Office of Finance', 'Surety Insurance', 'Finance'),
('6399', 'Office of Finance', 'Insurance Carriers, NEC', 'Finance'),
('6411', 'Office of Finance', 'Insurance Agents, Brokers & Service', 'Finance'),
('6500', 'Office of Finance', 'Real Estate', 'Finance'),
('6510', 'Office of Finance', 'Real Estate Operators & Lessors', 'Finance'),
('6512', 'Office of Finance', 'Operators of Apartment Buildings', 'Finance'),
('6513', 'Office of Finance', 'Operators of Real Property, NEC', 'Finance'),
('6519', 'Office of Finance', 'Real Property Lessors, NEC', 'Finance'),
('6531', 'Office of Finance', 'Real Estate Agents & Managers', 'Finance'),
('6532', 'Office of Finance', 'Real Estate Dealers (for Own Account)', 'Finance'),
('6552', 'Office of Finance', 'Land Subdividers & Developers', 'Finance'),
('6726', 'Office of Finance', 'Investment Offices, NEC', 'Finance'),
('6770', 'Office of Finance', 'Blank Checks', 'Finance'),
('6792', 'Office of Finance', 'Investment Trusts, NEC', 'Finance'),
('6794', 'Office of Finance', 'Patent Owners & Lessors', 'Finance'),
('6795', 'Office of Finance', 'Mineral Royalty Traders', 'Finance'),
('6798', 'Office of Finance', 'Real Estate Investment Trusts', 'Finance'),
('6799', 'Office of Finance', 'Investors, NEC', 'Finance'),
('6189', 'Office of Finance', 'Asset-Backed Securities', 'Finance'),
('6361', 'Office of Finance', 'Title Insurance', 'Finance'),
-- =========================================================================
-- Office of Real Estate & Construction (SIC 1500-1799, 6500-6553)
-- =========================================================================
('1500', 'Office of Real Estate & Construction', 'Building Construction General Contractors', 'Real Estate & Construction'),
('1520', 'Office of Real Estate & Construction', 'General Building Contractors, Residential', 'Real Estate & Construction'),
('1521', 'Office of Real Estate & Construction', 'General Contractors, Residential Buildings', 'Real Estate & Construction'),
('1531', 'Office of Real Estate & Construction', 'Operative Builders', 'Real Estate & Construction'),
('1540', 'Office of Real Estate & Construction', 'General Building Contractors, Nonresidential', 'Real Estate & Construction'),
('1541', 'Office of Real Estate & Construction', 'General Contractors, Industrial & Commercial', 'Real Estate & Construction'),
('1600', 'Office of Real Estate & Construction', 'Heavy Construction, Except Building', 'Real Estate & Construction'),
('1623', 'Office of Real Estate & Construction', 'Water, Sewer, Pipeline Construction', 'Real Estate & Construction'),
('1700', 'Office of Real Estate & Construction', 'Construction Special Trade Contractors', 'Real Estate & Construction'),
('1731', 'Office of Real Estate & Construction', 'Electrical Work', 'Real Estate & Construction'),
-- =========================================================================
-- Office of Energy & Transportation (SIC 1000-1499, 2900-2999, 4000-4799, 4900-4991)
-- =========================================================================
('1000', 'Office of Energy & Transportation', 'Metal Mining', 'Energy & Transportation'),
('1040', 'Office of Energy & Transportation', 'Gold and Silver Ores Mining', 'Energy & Transportation'),
('1090', 'Office of Energy & Transportation', 'Metal Mining Services', 'Energy & Transportation'),
('1220', 'Office of Energy & Transportation', 'Bituminous Coal & Lignite Mining', 'Energy & Transportation'),
('1221', 'Office of Energy & Transportation', 'Bituminous Coal & Lignite Surface Mining', 'Energy & Transportation'),
('1311', 'Office of Energy & Transportation', 'Crude Petroleum & Natural Gas', 'Energy & Transportation'),
('1381', 'Office of Energy & Transportation', 'Drilling Oil & Gas Wells', 'Energy & Transportation'),
('1382', 'Office of Energy & Transportation', 'Oil & Gas Field Services, NEC', 'Energy & Transportation'),
('1389', 'Office of Energy & Transportation', 'Services Allied to Oil & Gas Extraction', 'Energy & Transportation'),
('1400', 'Office of Energy & Transportation', 'Mining & Quarrying of Nonmetallic Minerals', 'Energy & Transportation'),
('2911', 'Office of Energy & Transportation', 'Petroleum Refining', 'Energy & Transportation'),
('2990', 'Office of Energy & Transportation', 'Petroleum & Coal Products, NEC', 'Energy & Transportation'),
('2999', 'Office of Energy & Transportation', 'Products of Petroleum & Coal, NEC', 'Energy & Transportation'),
('4011', 'Office of Energy & Transportation', 'Railroads, Line-Haul Operating', 'Energy & Transportation'),
('4013', 'Office of Energy & Transportation', 'Railroad Switching & Terminal Establishments', 'Energy & Transportation'),
('4100', 'Office of Energy & Transportation', 'Local & Suburban Transit', 'Energy & Transportation'),
('4210', 'Office of Energy & Transportation', 'Trucking & Courier Services (No Air)', 'Energy & Transportation'),
('4213', 'Office of Energy & Transportation', 'Trucking (Except Local)', 'Energy & Transportation'),
('4220', 'Office of Energy & Transportation', 'Public Warehousing & Storage', 'Energy & Transportation'),
('4231', 'Office of Energy & Transportation', 'Terminal & Joint Terminal Maintenance', 'Energy & Transportation'),
('4400', 'Office of Energy & Transportation', 'Water Transportation', 'Energy & Transportation'),
('4412', 'Office of Energy & Transportation', 'Deep Sea Foreign Transportation of Freight', 'Energy & Transportation'),
('4512', 'Office of Energy & Transportation', 'Air Transportation, Scheduled', 'Energy & Transportation'),
('4513', 'Office of Energy & Transportation', 'Air Courier Services', 'Energy & Transportation'),
('4522', 'Office of Energy & Transportation', 'Air Transportation, Nonscheduled', 'Energy & Transportation'),
('4581', 'Office of Energy & Transportation', 'Airports, Flying Fields & Airport Terminal Services', 'Energy & Transportation'),
('4610', 'Office of Energy & Transportation', 'Pipe Lines (No Natural Gas)', 'Energy & Transportation'),
('4700', 'Office of Energy & Transportation', 'Transportation Services', 'Energy & Transportation'),
('4731', 'Office of Energy & Transportation', 'Arrangement of Transportation of Freight & Cargo', 'Energy & Transportation'),
('4900', 'Office of Energy & Transportation', 'Electric, Gas & Sanitary Services', 'Energy & Transportation'),
('4911', 'Office of Energy & Transportation', 'Electric Services', 'Energy & Transportation'),
('4922', 'Office of Energy & Transportation', 'Natural Gas Transmission', 'Energy & Transportation'),
('4923', 'Office of Energy & Transportation', 'Natural Gas Transmission & Distribution', 'Energy & Transportation'),
('4924', 'Office of Energy & Transportation', 'Natural Gas Distribution', 'Energy & Transportation'),
('4931', 'Office of Energy & Transportation', 'Electric & Other Services Combined', 'Energy & Transportation'),
('4932', 'Office of Energy & Transportation', 'Gas & Other Services Combined', 'Energy & Transportation'),
('4941', 'Office of Energy & Transportation', 'Water Supply', 'Energy & Transportation'),
('4950', 'Office of Energy & Transportation', 'Sanitary Services', 'Energy & Transportation'),
('4953', 'Office of Energy & Transportation', 'Refuse Systems', 'Energy & Transportation'),
('4955', 'Office of Energy & Transportation', 'Hazardous Waste Management', 'Energy & Transportation'),
('4991', 'Office of Energy & Transportation', 'Cogeneration Services & Small Power Producers', 'Energy & Transportation'),
-- =========================================================================
-- Office of Manufacturing (SIC 2000-2799, 3000-3569, 3580-3599, 3700-3799, 3820-3825, 3860-3999)
-- =========================================================================
('2000', 'Office of Manufacturing', 'Food & Kindred Products', 'Manufacturing'),
('2011', 'Office of Manufacturing', 'Meat Packing Plants', 'Manufacturing'),
('2013', 'Office of Manufacturing', 'Sausages & Other Prepared Meats', 'Manufacturing'),
('2015', 'Office of Manufacturing', 'Poultry Slaughtering & Processing', 'Manufacturing'),
('2020', 'Office of Manufacturing', 'Dairy Products', 'Manufacturing'),
('2024', 'Office of Manufacturing', 'Ice Cream & Frozen Desserts', 'Manufacturing'),
('2030', 'Office of Manufacturing', 'Canned, Frozen & Preserved Fruits & Vegetables', 'Manufacturing'),
('2033', 'Office of Manufacturing', 'Canned Fruits, Vegetables & Preserves', 'Manufacturing'),
('2040', 'Office of Manufacturing', 'Grain Mill Products', 'Manufacturing'),
('2050', 'Office of Manufacturing', 'Bakery Products', 'Manufacturing'),
('2052', 'Office of Manufacturing', 'Cookies & Crackers', 'Manufacturing'),
('2060', 'Office of Manufacturing', 'Sugar & Confectionery Products', 'Manufacturing'),
('2070', 'Office of Manufacturing', 'Fats & Oils', 'Manufacturing'),
('2080', 'Office of Manufacturing', 'Beverages', 'Manufacturing'),
('2082', 'Office of Manufacturing', 'Malt Beverages', 'Manufacturing'),
('2086', 'Office of Manufacturing', 'Bottled & Canned Soft Drinks & Carbonated Water', 'Manufacturing'),
('2090', 'Office of Manufacturing', 'Food Preparations, NEC', 'Manufacturing'),
('2092', 'Office of Manufacturing', 'Prepared Fresh or Frozen Fish & Seafood', 'Manufacturing'),
('2100', 'Office of Manufacturing', 'Tobacco Products', 'Manufacturing'),
('2111', 'Office of Manufacturing', 'Cigarettes', 'Manufacturing'),
('2200', 'Office of Manufacturing', 'Textile Mill Products', 'Manufacturing'),
('2211', 'Office of Manufacturing', 'Broadwoven Fabric Mills, Cotton', 'Manufacturing'),
('2221', 'Office of Manufacturing', 'Broadwoven Fabric Mills, Man Made Fiber & Silk', 'Manufacturing'),
('2250', 'Office of Manufacturing', 'Knitting Mills', 'Manufacturing'),
('2253', 'Office of Manufacturing', 'Knit Outerwear Mills', 'Manufacturing'),
('2273', 'Office of Manufacturing', 'Carpets & Rugs', 'Manufacturing'),
('2300', 'Office of Manufacturing', 'Apparel & Other Finished Products', 'Manufacturing'),
('2320', 'Office of Manufacturing', 'Mens & Boys Furnishings, Work Clothing', 'Manufacturing'),
('2330', 'Office of Manufacturing', 'Womens, Misses & Juniors Outerwear', 'Manufacturing'),
('2340', 'Office of Manufacturing', 'Childrens Outerwear', 'Manufacturing'),
('2390', 'Office of Manufacturing', 'Fabricated Textile Products, NEC', 'Manufacturing'),
('2400', 'Office of Manufacturing', 'Lumber & Wood Products (No Furniture)', 'Manufacturing'),
('2421', 'Office of Manufacturing', 'Sawmills & Planing Mills, General', 'Manufacturing'),
('2430', 'Office of Manufacturing', 'Millwork, Veneer, Plywood & Structural Members', 'Manufacturing'),
('2451', 'Office of Manufacturing', 'Mobile Homes', 'Manufacturing'),
('2510', 'Office of Manufacturing', 'Household Furniture', 'Manufacturing'),
('2511', 'Office of Manufacturing', 'Wood Household Furniture', 'Manufacturing'),
('2520', 'Office of Manufacturing', 'Office Furniture', 'Manufacturing'),
('2522', 'Office of Manufacturing', 'Office Furniture (No Wood)', 'Manufacturing'),
('2531', 'Office of Manufacturing', 'Public Building & Related Furniture', 'Manufacturing'),
('2590', 'Office of Manufacturing', 'Miscellaneous Furniture & Fixtures', 'Manufacturing'),
('2600', 'Office of Manufacturing', 'Papers & Allied Products', 'Manufacturing'),
('2611', 'Office of Manufacturing', 'Pulp Mills', 'Manufacturing'),
('2621', 'Office of Manufacturing', 'Paper Mills', 'Manufacturing'),
('2631', 'Office of Manufacturing', 'Paperboard Mills', 'Manufacturing'),
('2650', 'Office of Manufacturing', 'Paperboard Containers & Boxes', 'Manufacturing'),
('2670', 'Office of Manufacturing', 'Converted Paper & Paperboard Products', 'Manufacturing'),
('2673', 'Office of Manufacturing', 'Plastics, Foil & Coated Paper Bags', 'Manufacturing'),
('2710', 'Office of Manufacturing', 'Newspapers: Publishing & Printing', 'Manufacturing'),
('2711', 'Office of Manufacturing', 'Newspapers: Publishing & Printing', 'Manufacturing'),
('2720', 'Office of Manufacturing', 'Periodicals: Publishing & Printing', 'Manufacturing'),
('2721', 'Office of Manufacturing', 'Periodicals: Publishing & Printing', 'Manufacturing'),
('2731', 'Office of Manufacturing', 'Books: Publishing & Printing', 'Manufacturing'),
('2732', 'Office of Manufacturing', 'Book Printing', 'Manufacturing'),
('2741', 'Office of Manufacturing', 'Miscellaneous Publishing', 'Manufacturing'),
('2750', 'Office of Manufacturing', 'Commercial Printing', 'Manufacturing'),
('2761', 'Office of Manufacturing', 'Manifold Business Forms', 'Manufacturing'),
('2780', 'Office of Manufacturing', 'Blankbooks, Looseleaf Binders & Devices', 'Manufacturing'),
('2790', 'Office of Manufacturing', 'Service Industries for the Printing Trade', 'Manufacturing'),
('2800', 'Office of Manufacturing', 'Chemicals & Allied Products', 'Manufacturing'),
('2810', 'Office of Manufacturing', 'Industrial Chemicals & Synthetics', 'Manufacturing'),
('2812', 'Office of Manufacturing', 'Alkalies & Chlorine', 'Manufacturing'),
('2813', 'Office of Manufacturing', 'Industrial Gases', 'Manufacturing'),
('2816', 'Office of Manufacturing', 'Inorganic Pigments', 'Manufacturing'),
('2819', 'Office of Manufacturing', 'Industrial Inorganic Chemicals, NEC', 'Manufacturing'),
('2820', 'Office of Manufacturing', 'Plastics Materials & Synthetic Resins', 'Manufacturing'),
('2821', 'Office of Manufacturing', 'Plastics Materials, Synthetic Resins & Nonvulcanizable Elastomers', 'Manufacturing'),
('2822', 'Office of Manufacturing', 'Synthetic Rubber', 'Manufacturing'),
('2823', 'Office of Manufacturing', 'Cellulosic Manmade Fibers', 'Manufacturing'),
('2824', 'Office of Manufacturing', 'Manmade Organic Fibers (No Cellulosic)', 'Manufacturing'),
('2841', 'Office of Manufacturing', 'Soap & Other Detergents (Except Specialty Cleaning)', 'Manufacturing'),
('2851', 'Office of Manufacturing', 'Paints, Varnishes, Lacquers & Allied Products', 'Manufacturing'),
('2860', 'Office of Manufacturing', 'Industrial Chemicals & Synthetics', 'Manufacturing'),
('2869', 'Office of Manufacturing', 'Industrial Organic Chemicals, NEC', 'Manufacturing'),
('2870', 'Office of Manufacturing', 'Agricultural Chemicals', 'Manufacturing'),
('2891', 'Office of Manufacturing', 'Adhesives & Sealants', 'Manufacturing'),
('2899', 'Office of Manufacturing', 'Chemicals & Chemical Preparations, NEC', 'Manufacturing'),
('3000', 'Office of Manufacturing', 'Rubber & Misc Plastics Products', 'Manufacturing'),
('3011', 'Office of Manufacturing', 'Tires & Inner Tubes', 'Manufacturing'),
('3021', 'Office of Manufacturing', 'Rubber & Plastics Footwear', 'Manufacturing'),
('3050', 'Office of Manufacturing', 'Gaskets, Packing & Sealing Devices', 'Manufacturing'),
('3060', 'Office of Manufacturing', 'Fabricated Rubber Products, NEC', 'Manufacturing'),
('3080', 'Office of Manufacturing', 'Plastics Products Manufacturing', 'Manufacturing'),
('3081', 'Office of Manufacturing', 'Plastics Plumbing Fixtures', 'Manufacturing'),
('3086', 'Office of Manufacturing', 'Plastics Foam Products', 'Manufacturing'),
('3089', 'Office of Manufacturing', 'Plastics Products Manufacturing, NEC', 'Manufacturing'),
('3100', 'Office of Manufacturing', 'Leather & Leather Products', 'Manufacturing'),
('3140', 'Office of Manufacturing', 'Footwear (No Rubber)', 'Manufacturing'),
('3211', 'Office of Manufacturing', 'Flat Glass', 'Manufacturing'),
('3220', 'Office of Manufacturing', 'Glass & Glassware, Pressed or Blown', 'Manufacturing'),
('3221', 'Office of Manufacturing', 'Glass Containers', 'Manufacturing'),
('3231', 'Office of Manufacturing', 'Glass Products Made of Purchased Glass', 'Manufacturing'),
('3241', 'Office of Manufacturing', 'Cement, Hydraulic', 'Manufacturing'),
('3250', 'Office of Manufacturing', 'Structural Clay Products', 'Manufacturing'),
('3270', 'Office of Manufacturing', 'Concrete, Gypsum & Plaster Products', 'Manufacturing'),
('3272', 'Office of Manufacturing', 'Concrete Products (No Block & Brick)', 'Manufacturing'),
('3281', 'Office of Manufacturing', 'Cut Stone & Stone Products', 'Manufacturing'),
('3290', 'Office of Manufacturing', 'Abrasive, Asbestos & Misc Nonmetallic Mineral Products', 'Manufacturing'),
('3310', 'Office of Manufacturing', 'Steel Works, Blast Furnaces & Rolling & Finishing Mills', 'Manufacturing'),
('3312', 'Office of Manufacturing', 'Steel Works, Blast Furnaces (Incl Coke Ovens)', 'Manufacturing'),
('3317', 'Office of Manufacturing', 'Steel Pipe & Tubes', 'Manufacturing'),
('3320', 'Office of Manufacturing', 'Iron & Steel Foundries', 'Manufacturing'),
('3330', 'Office of Manufacturing', 'Primary Smelting & Refining of Nonferrous Metals', 'Manufacturing'),
('3334', 'Office of Manufacturing', 'Primary Production of Aluminum', 'Manufacturing'),
('3340', 'Office of Manufacturing', 'Secondary Smelting & Refining of Nonferrous Metals', 'Manufacturing'),
('3350', 'Office of Manufacturing', 'Rolling, Drawing & Extruding of Nonferrous Metals', 'Manufacturing'),
('3357', 'Office of Manufacturing', 'Drawing & Insulating of Nonferrous Metals', 'Manufacturing'),
('3360', 'Office of Manufacturing', 'Nonferrous Foundries (Castings)', 'Manufacturing'),
('3390', 'Office of Manufacturing', 'Misc Primary Metal Products', 'Manufacturing'),
('3411', 'Office of Manufacturing', 'Metal Cans', 'Manufacturing'),
('3412', 'Office of Manufacturing', 'Metal Shipping Barrels, Drums, Kegs & Pails', 'Manufacturing'),
('3420', 'Office of Manufacturing', 'Cutlery, Handtools & General Hardware', 'Manufacturing'),
('3421', 'Office of Manufacturing', 'Cutlery, Handtools & General Hardware', 'Manufacturing'),
('3430', 'Office of Manufacturing', 'Heating Equipment & Plumbing Fixtures', 'Manufacturing'),
('3433', 'Office of Manufacturing', 'Heating Equipment, Except Electric & Warm Air Furnaces', 'Manufacturing'),
('3440', 'Office of Manufacturing', 'Fabricated Structural Metal Manufacturing', 'Manufacturing'),
('3442', 'Office of Manufacturing', 'Metal Doors, Sash, Frames, Molding & Trim', 'Manufacturing'),
('3443', 'Office of Manufacturing', 'Fabricated Plate Work (Boiler Shops)', 'Manufacturing'),
('3444', 'Office of Manufacturing', 'Sheet Metal Work', 'Manufacturing'),
('3448', 'Office of Manufacturing', 'Prefabricated Metal Buildings & Components', 'Manufacturing'),
('3451', 'Office of Manufacturing', 'Screw Machine Products', 'Manufacturing'),
('3452', 'Office of Manufacturing', 'Bolts, Nuts, Screws, Rivets & Washers', 'Manufacturing'),
('3460', 'Office of Manufacturing', 'Metal Forgings & Stampings', 'Manufacturing'),
('3470', 'Office of Manufacturing', 'Services to Buildings & Dwellings', 'Manufacturing'),
('3480', 'Office of Manufacturing', 'Ordnance & Accessories, NEC', 'Manufacturing'),
('3489', 'Office of Manufacturing', 'Ordnance & Accessories, NEC', 'Manufacturing'),
('3490', 'Office of Manufacturing', 'Misc Fabricated Metal Products', 'Manufacturing'),
('3491', 'Office of Manufacturing', 'Industrial Valves', 'Manufacturing'),
('3492', 'Office of Manufacturing', 'Fluid Power Valves & Hose Fittings', 'Manufacturing'),
('3493', 'Office of Manufacturing', 'Steel Springs, Except Wire', 'Manufacturing'),
('3494', 'Office of Manufacturing', 'Valves & Pipe Fittings, NEC', 'Manufacturing'),
('3499', 'Office of Manufacturing', 'Metal Services, NEC', 'Manufacturing'),
('3510', 'Office of Manufacturing', 'Engines & Turbines', 'Manufacturing'),
('3523', 'Office of Manufacturing', 'Farm Machinery & Equipment', 'Manufacturing'),
('3524', 'Office of Manufacturing', 'Lawn & Garden Tractors & Equipment', 'Manufacturing'),
('3530', 'Office of Manufacturing', 'Construction, Mining & Materials Handling Equipment', 'Manufacturing'),
('3531', 'Office of Manufacturing', 'Construction Machinery & Equipment', 'Manufacturing'),
('3532', 'Office of Manufacturing', 'Mining Machinery & Equipment', 'Manufacturing'),
('3533', 'Office of Manufacturing', 'Oil & Gas Field Machinery & Equipment', 'Manufacturing'),
('3537', 'Office of Manufacturing', 'Industrial Trucks, Tractors, Trailers & Stackers', 'Manufacturing'),
('3540', 'Office of Manufacturing', 'Metalworking Machinery & Equipment', 'Manufacturing'),
('3541', 'Office of Manufacturing', 'Machine Tools, Metal Cutting Types', 'Manufacturing'),
('3550', 'Office of Manufacturing', 'Special Industry Machinery (No Metalworking)', 'Manufacturing'),
('3555', 'Office of Manufacturing', 'Printing Trades Machinery & Equipment', 'Manufacturing'),
('3556', 'Office of Manufacturing', 'Food Products Machinery', 'Manufacturing'),
('3559', 'Office of Manufacturing', 'Special Industry Machinery, NEC', 'Manufacturing'),
('3560', 'Office of Manufacturing', 'General Industrial Machinery & Equipment', 'Manufacturing'),
('3561', 'Office of Manufacturing', 'Pumps & Pumping Equipment', 'Manufacturing'),
('3562', 'Office of Manufacturing', 'Ball & Roller Bearings', 'Manufacturing'),
('3564', 'Office of Manufacturing', 'Industrial & Commercial Fans & Blowers', 'Manufacturing'),
('3567', 'Office of Manufacturing', 'Industrial Process Furnaces & Ovens', 'Manufacturing'),
('3569', 'Office of Manufacturing', 'General Industrial Machinery & Equipment, NEC', 'Manufacturing'),
('3580', 'Office of Manufacturing', 'Refrigeration & Heating Equipment', 'Manufacturing'),
('3585', 'Office of Manufacturing', 'Air-Conditioning & Warm Air Heating Equipment', 'Manufacturing'),
('3589', 'Office of Manufacturing', 'Industrial & Commercial Machinery, NEC', 'Manufacturing'),
('3590', 'Office of Manufacturing', 'Misc Industrial & Commercial Machinery & Equipment', 'Manufacturing'),
('3599', 'Office of Manufacturing', 'Industrial & Commercial Machinery, NEC', 'Manufacturing'),
('3711', 'Office of Manufacturing', 'Motor Vehicles & Passenger Car Bodies', 'Manufacturing'),
('3713', 'Office of Manufacturing', 'Truck Trailers', 'Manufacturing'),
('3714', 'Office of Manufacturing', 'Motor Vehicle Parts & Accessories', 'Manufacturing'),
('3715', 'Office of Manufacturing', 'Truck Trailers', 'Manufacturing'),
('3716', 'Office of Manufacturing', 'Motor Homes', 'Manufacturing'),
('3720', 'Office of Manufacturing', 'Aircraft & Parts', 'Manufacturing'),
('3721', 'Office of Manufacturing', 'Aircraft', 'Manufacturing'),
('3724', 'Office of Manufacturing', 'Aircraft Engines & Engine Parts', 'Manufacturing'),
('3728', 'Office of Manufacturing', 'Aircraft Parts & Auxiliary Equipment, NEC', 'Manufacturing'),
('3730', 'Office of Manufacturing', 'Ship & Boat Building & Repairing', 'Manufacturing'),
('3743', 'Office of Manufacturing', 'Railroad Equipment', 'Manufacturing'),
('3751', 'Office of Manufacturing', 'Motorcycles, Bicycles & Parts', 'Manufacturing'),
('3760', 'Office of Manufacturing', 'Guided Missiles & Space Vehicles & Parts', 'Manufacturing'),
('3769', 'Office of Manufacturing', 'Guided Missiles & Space Vehicles, NEC', 'Manufacturing'),
('3790', 'Office of Manufacturing', 'Misc Transportation Equipment', 'Manufacturing'),
('3795', 'Office of Manufacturing', 'Tanks & Tank Components', 'Manufacturing'),
('3822', 'Office of Manufacturing', 'Automatic Controls for Temperature Regulation', 'Manufacturing'),
('3823', 'Office of Manufacturing', 'Industrial Instruments for Measurement', 'Manufacturing'),
('3824', 'Office of Manufacturing', 'Industrial Instruments for Measurement, Totalizing Fluid Meters', 'Manufacturing'),
('3825', 'Office of Manufacturing', 'Instruments for Measuring & Testing of Electricity', 'Manufacturing'),
('3829', 'Office of Manufacturing', 'Measuring & Controlling Devices, NEC', 'Manufacturing'),
('3861', 'Office of Manufacturing', 'Photographic Equipment & Supplies', 'Manufacturing'),
('3873', 'Office of Manufacturing', 'Watches, Clocks & Clockwork Operated Devices', 'Manufacturing'),
('3911', 'Office of Manufacturing', 'Jewelry, Precious Metal', 'Manufacturing'),
('3931', 'Office of Manufacturing', 'Musical Instruments', 'Manufacturing'),
('3942', 'Office of Manufacturing', 'Dolls & Stuffed Toys', 'Manufacturing'),
('3944', 'Office of Manufacturing', 'Games, Toys & Childrens Vehicles', 'Manufacturing'),
('3949', 'Office of Manufacturing', 'Sporting & Athletic Goods, NEC', 'Manufacturing'),
('3950', 'Office of Manufacturing', 'Pens, Pencils & Artists Materials', 'Manufacturing'),
('3960', 'Office of Manufacturing', 'Costume Jewelry & Novelties', 'Manufacturing'),
('3990', 'Office of Manufacturing', 'Miscellaneous Manufacturing Industries', 'Manufacturing'),
('3993', 'Office of Manufacturing', 'Signs & Advertising Specialties', 'Manufacturing'),
('3999', 'Office of Manufacturing', 'Manufacturing Industries, NEC', 'Manufacturing'),
('2890', 'Office of Manufacturing', 'Industrial Chemicals, NEC', 'Manufacturing'),
('3341', 'Office of Manufacturing', 'Secondary Smelting of Nonferrous Metals', 'Manufacturing'),
('3821', 'Office of Manufacturing', 'Laboratory Apparatus & Furniture', 'Manufacturing'),
('3910', 'Office of Manufacturing', 'Jewelry, Silverware & Plated Ware', 'Manufacturing'),
-- =========================================================================
-- Office of Trade & Services (SIC 5000-5199, 5200-5999 (excl 5912), 7000-7369, 7500-7999)
-- =========================================================================
('5000', 'Office of Trade & Services', 'Durable Goods, Wholesale', 'Trade & Services'),
('5010', 'Office of Trade & Services', 'Motor Vehicles & Motor Vehicle Parts & Supplies', 'Trade & Services'),
('5013', 'Office of Trade & Services', 'Motor Vehicle Supplies & New Parts', 'Trade & Services'),
('5020', 'Office of Trade & Services', 'Furniture & Homefurnishings', 'Trade & Services'),
('5030', 'Office of Trade & Services', 'Lumber & Other Construction Materials', 'Trade & Services'),
('5040', 'Office of Trade & Services', 'Professional & Commercial Equipment & Supplies', 'Trade & Services'),
('5045', 'Office of Trade & Services', 'Computers & Peripherals & Software', 'Trade & Services'),
('5050', 'Office of Trade & Services', 'Metals & Minerals (No Petroleum)', 'Trade & Services'),
('5051', 'Office of Trade & Services', 'Metals Service Centers & Offices', 'Trade & Services'),
('5063', 'Office of Trade & Services', 'Electrical Apparatus & Equipment, Wiring Supplies', 'Trade & Services'),
('5064', 'Office of Trade & Services', 'Electrical Appliances, Television & Radio Sets', 'Trade & Services'),
('5065', 'Office of Trade & Services', 'Electronic Parts & Equipment, NEC', 'Trade & Services'),
('5070', 'Office of Trade & Services', 'Hardware & Plumbing & Heating Equipment & Supplies', 'Trade & Services'),
('5080', 'Office of Trade & Services', 'Industrial & Personal Service Paper', 'Trade & Services'),
('5082', 'Office of Trade & Services', 'Construction & Mining Machinery & Equipment', 'Trade & Services'),
('5084', 'Office of Trade & Services', 'Industrial Machinery & Equipment', 'Trade & Services'),
('5090', 'Office of Trade & Services', 'Durable Goods, NEC', 'Trade & Services'),
('5094', 'Office of Trade & Services', 'Jewelry, Watches & Precious Stones', 'Trade & Services'),
('5099', 'Office of Trade & Services', 'Durable Goods, NEC', 'Trade & Services'),
('5110', 'Office of Trade & Services', 'Paper & Paper Products', 'Trade & Services'),
('5130', 'Office of Trade & Services', 'Apparel, Piece Goods & Notions', 'Trade & Services'),
('5140', 'Office of Trade & Services', 'Groceries & Related Products, NEC', 'Trade & Services'),
('5141', 'Office of Trade & Services', 'Groceries, General Line', 'Trade & Services'),
('5150', 'Office of Trade & Services', 'Farm-Product Raw Materials', 'Trade & Services'),
('5160', 'Office of Trade & Services', 'Chemicals & Allied Products', 'Trade & Services'),
('5171', 'Office of Trade & Services', 'Petroleum & Petroleum Products (No Bulk Stations)', 'Trade & Services'),
('5172', 'Office of Trade & Services', 'Petroleum Products, NEC', 'Trade & Services'),
('5180', 'Office of Trade & Services', 'Beer, Wine & Distilled Alcoholic Beverages', 'Trade & Services'),
('5190', 'Office of Trade & Services', 'Misc Nondurable Goods, Wholesale', 'Trade & Services'),
('5200', 'Office of Trade & Services', 'Retail Stores, Building Materials & Garden Supplies', 'Trade & Services'),
('5211', 'Office of Trade & Services', 'Lumber & Other Building Materials Dealers', 'Trade & Services'),
('5271', 'Office of Trade & Services', 'Mobile Home Dealers', 'Trade & Services'),
('5311', 'Office of Trade & Services', 'Department Stores', 'Trade & Services'),
('5331', 'Office of Trade & Services', 'Variety Stores', 'Trade & Services'),
('5399', 'Office of Trade & Services', 'Misc General Merchandise Stores', 'Trade & Services'),
('5400', 'Office of Trade & Services', 'Retail Stores, Food', 'Trade & Services'),
('5411', 'Office of Trade & Services', 'Grocery Stores', 'Trade & Services'),
('5412', 'Office of Trade & Services', 'Convenience Stores', 'Trade & Services'),
('5500', 'Office of Trade & Services', 'Retail Stores, Auto Dealers & Gas Stations', 'Trade & Services'),
('5531', 'Office of Trade & Services', 'Auto & Home Supply Stores', 'Trade & Services'),
('5600', 'Office of Trade & Services', 'Retail Stores, Apparel & Accessory', 'Trade & Services'),
('5621', 'Office of Trade & Services', 'Womens Clothing Stores', 'Trade & Services'),
('5651', 'Office of Trade & Services', 'Family Clothing Stores', 'Trade & Services'),
('5661', 'Office of Trade & Services', 'Shoe Stores', 'Trade & Services'),
('5700', 'Office of Trade & Services', 'Retail Stores, Home Furniture & Equipment', 'Trade & Services'),
('5712', 'Office of Trade & Services', 'Furniture Stores', 'Trade & Services'),
('5731', 'Office of Trade & Services', 'Radio, Television & Consumer Electronics Stores', 'Trade & Services'),
('5734', 'Office of Trade & Services', 'Computer & Computer Software Stores', 'Trade & Services'),
('5735', 'Office of Trade & Services', 'Record & Prerecorded Tape Stores', 'Trade & Services'),
('5810', 'Office of Trade & Services', 'Eating & Drinking Places', 'Trade & Services'),
('5812', 'Office of Trade & Services', 'Eating Places', 'Trade & Services'),
('5900', 'Office of Trade & Services', 'Retail Stores, Misc', 'Trade & Services'),
('5940', 'Office of Trade & Services', 'Sporting Goods & Bicycle Shops', 'Trade & Services'),
('5944', 'Office of Trade & Services', 'Jewelry Stores', 'Trade & Services'),
('5945', 'Office of Trade & Services', 'Hobby, Toy & Game Shops', 'Trade & Services'),
('5947', 'Office of Trade & Services', 'Gift, Novelty & Souvenir Shops', 'Trade & Services'),
('5960', 'Office of Trade & Services', 'Retail Stores, NEC - Nonstore Retailers', 'Trade & Services'),
('5961', 'Office of Trade & Services', 'Catalog & Mail-Order Houses', 'Trade & Services'),
('5990', 'Office of Trade & Services', 'Retail Stores, NEC', 'Trade & Services'),
('5999', 'Office of Trade & Services', 'Retail Stores, NEC', 'Trade & Services'),
('7000', 'Office of Trade & Services', 'Hotels, Rooming Houses, Camps & Other Lodging', 'Trade & Services'),
('7011', 'Office of Trade & Services', 'Hotels & Motels', 'Trade & Services'),
('7200', 'Office of Trade & Services', 'Laundry, Cleaning, Garment Services', 'Trade & Services'),
('7310', 'Office of Trade & Services', 'Services-Advertising', 'Trade & Services'),
('7311', 'Office of Trade & Services', 'Advertising Services', 'Trade & Services'),
('7312', 'Office of Trade & Services', 'Advertising Services', 'Trade & Services'),
('7320', 'Office of Trade & Services', 'Services-Credit Reporting & Collection', 'Trade & Services'),
('7330', 'Office of Trade & Services', 'Mailing, Reproduction & Stenographic Services', 'Trade & Services'),
('7340', 'Office of Trade & Services', 'Services to Buildings & Dwellings', 'Trade & Services'),
('7350', 'Office of Trade & Services', 'Misc Equipment Rental & Leasing', 'Trade & Services'),
('7359', 'Office of Trade & Services', 'Equipment Rental & Leasing, NEC', 'Trade & Services'),
('7361', 'Office of Trade & Services', 'Help Supply Services', 'Trade & Services'),
('7363', 'Office of Trade & Services', 'Help Supply Services', 'Trade & Services'),
('7500', 'Office of Trade & Services', 'Automotive Repair, Services & Parking', 'Trade & Services'),
('7510', 'Office of Trade & Services', 'Automotive Rental & Leasing', 'Trade & Services'),
('7600', 'Office of Trade & Services', 'Miscellaneous Repair Services', 'Trade & Services'),
('7812', 'Office of Trade & Services', 'Motion Picture & Tape Distribution', 'Trade & Services'),
('7819', 'Office of Trade & Services', 'Services Allied to Motion Picture Production', 'Trade & Services'),
('7822', 'Office of Trade & Services', 'Motion Picture Distribution (Non-Theatrical)', 'Trade & Services'),
('7841', 'Office of Trade & Services', 'Video Tape Rental', 'Trade & Services'),
('7900', 'Office of Trade & Services', 'Amusement & Recreation Services', 'Trade & Services'),
('7941', 'Office of Trade & Services', 'Professional Sports Clubs', 'Trade & Services'),
('7948', 'Office of Trade & Services', 'Racing, Including Track Operation', 'Trade & Services'),
('7990', 'Office of Trade & Services', 'Services, NEC', 'Trade & Services'),
('7997', 'Office of Trade & Services', 'Membership Sports & Recreation Clubs', 'Trade & Services'),
('7999', 'Office of Trade & Services', 'Amusement & Recreation Services, NEC', 'Trade & Services'),
('8200', 'Office of Trade & Services', 'Educational Services', 'Trade & Services'),
('8300', 'Office of Trade & Services', 'Social Services', 'Trade & Services'),
('8351', 'Office of Trade & Services', 'Child Day Care Services', 'Trade & Services'),
('8600', 'Office of Trade & Services', 'Membership Organizations', 'Trade & Services'),
('8900', 'Office of Trade & Services', 'Services, NEC', 'Trade & Services'),
('5031', 'Office of Trade & Services', 'Lumber & Construction Materials, Wholesale', 'Trade & Services'),
('5072', 'Office of Trade & Services', 'Hardware & Plumbing & Heating Equipment, Wholesale', 'Trade & Services'),
('7331', 'Office of Trade & Services', 'Mailing, Reproduction & Stenographic Services', 'Trade & Services'),
('7830', 'Office of Trade & Services', 'Motion Picture & Videotape Distribution', 'Trade & Services'),
('8111', 'Office of Trade & Services', 'Legal Services', 'Trade & Services'),
-- =========================================================================
-- Office of Crypto Assets (emerging — no legacy SIC codes assigned yet)
-- =========================================================================
-- Note: Crypto-focused companies typically file under 6199 (Finance Services)
-- or 7372 (Software). The SEC Office of Crypto Assets handles review but
-- does not have dedicated SIC codes. Mapping is done at filing review level.
-- =========================================================================
-- Office of Structured Finance (subset of 6000 range — SPVs, CLOs, ABS)
-- =========================================================================
-- Note: Structured finance vehicles (CLOs, CMBS, ABS trusts) typically use
-- SIC codes in the 6100-6199 range. The SEC Office of Structured Finance
-- handles their review. These remain mapped to 'Finance' sector as their
-- SIC codes overlap with general finance.
-- =========================================================================
-- Other (Agriculture, Government, Nonclassifiable)
-- =========================================================================
('0100', 'Other', 'Crops', 'Other'),
('0200', 'Other', 'Livestock & Animal Specialties', 'Other'),
('0700', 'Other', 'Agricultural Services', 'Other'),
('0800', 'Other', 'Forestry', 'Other'),
('0900', 'Other', 'Fishing, Hunting & Trapping', 'Other'),
('8880', 'Other', 'American Depositary Receipts', 'Other'),
('8888', 'Other', 'Foreign Governments', 'Other'),
('9111', 'Other', 'Executive Offices', 'Other'),
('9199', 'Other', 'General Government, NEC', 'Other'),
('9311', 'Other', 'Finance, Taxation & Monetary Policy', 'Other'),
('9500', 'Other', 'Environmental Quality & Housing', 'Other'),
('9611', 'Other', 'Administration of General Economic Programs', 'Other'),
('9621', 'Other', 'Regulation & Administration of Transportation', 'Other'),
('9631', 'Other', 'Regulation of Utilities', 'Other'),
('9651', 'Other', 'Regulation of Misc Commercial Sectors', 'Other'),
('9711', 'Other', 'National Security', 'Other'),
('9995', 'Other', 'Nonclassifiable Establishments', 'Other');

-- =============================================================================
-- Verification
-- =============================================================================
-- SELECT SECTOR, COUNT(*) AS codes FROM SIC_CODES GROUP BY 1 ORDER BY 2 DESC;
-- SELECT OFFICE, COUNT(*) AS codes FROM SIC_CODES GROUP BY 1 ORDER BY 2 DESC;
